# 00-vlan-manager-configmap.yaml                                                           
#                                                                                          
# This ConfigMap is used to configure the VLAN Manager for Linode LKE.                     
# It holds important networking parameters like subnet, VLAN labels, destination routes,   
# and Linode CLI configurations to automate VLAN and route attachment.                     
#                                                                                          
# -----------------------------------------------------                                    
# 📝 Parameters:                                                                           
#                                                                                          
# 1️⃣ SUBNET          - The primary subnet for VLAN interfaces.                             
# 2️⃣ ROUTE_IP        - The gateway IP for the primary subnet.                              
# 3️⃣ VLAN_LABEL      - The label identifier for the VLAN in Linode.                        
# 4️⃣ DEST_SUBNET     - The destination subnet for routing.                                 
# 5️⃣ KUBECONFIG      - The path to the Kubernetes config file for management.              
# 6️⃣ LINODE_CLI_CONFIG - Contains Linode CLI credentials and region settings.              
#                                                                                          
# -----------------------------------------------------                                    
# 🔄 Usage:                                                                                
#                                                                                          
# - This ConfigMap is mounted in the VLAN Manager DaemonSet.                               
# - It is used by the Linode CLI and networking scripts to configure VLAN routes           
#   and manage IP allocations.                                                             
#                                                                                          
# -----------------------------------------------------                                    
# ⚠️ Security Warning:                                                                     
#                                                                                          
# - Make sure to **encrypt sensitive tokens** before deploying to production.              
# - Avoid hardcoding access tokens directly in ConfigMaps if possible.                     
#                                                                                          
# -----------------------------------------------------                                    
# 🖋️ Author:                                                                               
# - Sandip Gangdhar                                                                        
# - GitHub: https://github.com/sandipgangdhar                                              
#                                                                                          
# © Linode-LKE-Private-Network | Developed by Sandip Gangdhar | 2025                       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vlan-manager-config
  namespace: kube-system
data:
  # ==========================
  # Route Push Configuration
  # ==========================
  # Set ENABLE_PUSH_ROUTE to "true" if your LKE cluster needs to communicate
  # with external resources (e.g., AWS, Azure) over a Site-to-Site VPN.
  #
  # If set to "false", no static route will be pushed, and the values below
  # (ROUTE_IP and DEST_SUBNET) will be ignored.
  #
  # ROUTE_IP:      The internal gateway IP (usually the VLAN interface on the VPN server).
  # DEST_SUBNET:   The destination subnet that should be routed through the VPN.
  #
  # Note: These values must still be defined even if route push is disabled,
  # so provide placeholder values (e.g., 0.0.0.0) if not used.

  # Set to "false" if VPN route is not needed
  ENABLE_PUSH_ROUTE: "true"

  # Taking the input for routes 
  # route_ip is Gateway IP for the subnet normally your NAT gateway VLAN IP 
  # dest_subnet is Destination subnet for static routing e.g. your AWS or GCP subnet
  ROUTE_LIST: |
    - route_ip: "172.16.0.1"
      dest_subnet: "192.168.0.0/16"
    - route_ip: "172.16.0.1"
      dest_subnet: "10.1.0.0/16"

  # Set to "false" if You don't want to attach the Firewall to LKE Cluster
  ENABLE_FIREWALL: "true"

  # Linode LKE Cluster ID (used for dynamic firewall attachment)
  LKE_CLUSTER_ID: "498743"

  # Primary subnet/Lindoe side VLAN interfaces subnet
  SUBNET: "172.16.0.0/12"

  # Linod Region Name 
  REGION: "in-maa"

  # VLAN label used in Linode VLAN configration
  VLAN_LABEL: "Linode-AWS"

  # Path to the Kubeconfig file for managing Kubernetes
  KUBECONFIG: "/tmp/kubeconfig"

  # Path to the Kubeconfig file for managing Kubernetes
  LINODE_API_KEY: "csdjhbsahfbashjfbsajhfbsjhafbsjhbfjkhbfkjhasbfkasbnfksanksakafkn"

  # Linode CLI configuration details
  LINODE_CLI_CONFIG: |
      [DEFAULT]
      default-user = sgangdha
      
      [sgangdha]
      token = csdjhbsahfbashjfbsajhfbsjhafbsjhbfjkhbfkjhasbfkasbnfksanksakafkn
      region = in-maa
      authorized_users = sgangdha
      suppress-version-warning = true
