apiVersion: v1
kind: ConfigMap
metadata:
  name: vlan-manager-config
  namespace: kube-system
data:
  SUBNET: "10.180.0.0/24"
  ROUTE_IP: "10.180.0.2"
  VLAN_LABEL: "private-lan"
  DEST_SUBNET: "10.180.2.0/24"
  KUBECONFIG: "/tmp/kubeconfig"
  LINODE_CLI_CONFIG: |
      [DEFAULT]
      default-user = sandip_akamai
            
      [sandip_akamai]
      token = ksdjbkjdsbvhkdsbvkdsnkdvnb
      region = in-maa
      authorized_users = sandip_akamai
      suppress-version-warning = true
