# 00-vlan-manager-configmap.yaml                                                           
#                                                                                          
# This ConfigMap is used to configure the VLAN Manager for Linode LKE.                     
# It holds important networking parameters like subnet, VLAN labels, destination routes,   
# and Linode CLI configurations to automate VLAN and route attachment.                     
#                                                                                          
# -----------------------------------------------------                                    
# 📝 Parameters:                                                                           
#                                                                                          
# 1️⃣ SUBNET          - The primary subnet for VLAN interfaces.                             
# 2️⃣ ROUTE_IP        - The gateway IP for the primary subnet.                              
# 3️⃣ VLAN_LABEL      - The label identifier for the VLAN in Linode.                        
# 4️⃣ DEST_SUBNET     - The destination subnet for routing.                                 
# 5️⃣ KUBECONFIG      - The path to the Kubernetes config file for management.              
# 6️⃣ LINODE_CLI_CONFIG - Contains Linode CLI credentials and region settings.              
#                                                                                          
# -----------------------------------------------------                                    
# 🔄 Usage:                                                                                
#                                                                                          
# - This ConfigMap is mounted in the VLAN Manager DaemonSet.                               
# - It is used by the Linode CLI and networking scripts to configure VLAN routes           
#   and manage IP allocations.                                                             
#                                                                                          
# -----------------------------------------------------                                    
# ⚠️ Security Warning:                                                                     
#                                                                                          
# - Make sure to **encrypt sensitive tokens** before deploying to production.              
# - Avoid hardcoding access tokens directly in ConfigMaps if possible.                     
#                                                                                          
# -----------------------------------------------------                                    
# 🖋️ Author:                                                                               
# - Sandip Gangdhar                                                                        
# - GitHub: https://github.com/sandipgangdhar                                              
#                                                                                          
# © Linode-LKE-Private-Network | Developed by Sandip Gangdhar | 2025                       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vlan-manager-config
  namespace: kube-system
data:
  # Primary subnet/Lindoe side VLAN interfaces subnet
  SUBNET: "172.16.0.0/12"

  # Linod Region Name 
  REGION: "in-maa"

  # Gateway IP for the primary subnet
  ROUTE_IP: "172.16.0.1"
 
  # VLAN label used in Linode VLAN configration
  VLAN_LABEL: "private-lan"

  # Destination subnet for static routing
  DEST_SUBNET: "10.0.0.0/16"

  # Path to the Kubeconfig file for managing Kubernetes
  KUBECONFIG: "/tmp/kubeconfig"

  # Path to the Kubeconfig file for managing Kubernetes
  LINODE_API_KEY: <YOUR LINODE API KEY>

  # Linode CLI configuration details
  LINODE_CLI_CONFIG: |
      [DEFAULT]
      default-user = sgangdha
      
      [sgangdha]
      token = <YOUR LINODE API KEY>
      region = in-maa
      plugin-obj-access-key = RCWTMC4K2KX2GUZQTDWQ
      plugin-obj-secret-key = iYwHRnrZ2f3TMG4f63Vo2vM3E9rgcvKDglUAezYy
      plugin-obj-cluster = in-bom-2
      authorized_users = sgangdha
      suppress-version-warning = true
