apiVersion: apps/v1
kind: Deployment
metadata:
  name: vlan-leader-manager
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlan-leader-manager
  template:
    metadata:
      labels:
        app: vlan-leader-manager
    spec:
      serviceAccountName: vlan-manager-sa
      containers:
        - name: vlan-leader-manager
          image: python:3.9
          command: ["/bin/bash", "-c"]
          args: 
            - |
              pip install flask flask-cors && \
              cp --dereference /root/scripts/06-rest-api.py /tmp/06-rest-api.py && \
              chmod u+x /tmp/06-rest-api.py && \
              exec python3 /tmp/06-rest-api.py > /tmp/flask.log 2>&1
          volumeMounts:
            - name: vlan-manager-scripts
              mountPath: /root/scripts
            - name: vlan-ip-storage
              mountPath: /mnt/vlan-ip

      volumes:
        - name: vlan-manager-scripts
          configMap:
            name: vlan-manager-scripts
        - name: vlan-ip-storage
          persistentVolumeClaim:
            claimName: vlan-ip-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vlan-leader-service
  namespace: kube-system
spec:
  selector:
    app: vlan-leader-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
