apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: kube-system
  labels:
    app: etcd
spec:
  clusterIP: None
  selector:
    app: etcd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: kube-system
spec:
  serviceName: "etcd"
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.12
        command:
          - /usr/local/bin/etcd
        args:
          - --name=$(POD_NAME)
          - --data-dir=/etcd-data
          - --initial-advertise-peer-urls=http://$(POD_NAME).etcd.kube-system.svc.cluster.local:2380
          - --listen-peer-urls=http://0.0.0.0:2380
          - --listen-client-urls=http://0.0.0.0:2379
          - --advertise-client-urls=http://$(POD_NAME).etcd.kube-system.svc.cluster.local:2379
          - --initial-cluster=etcd-0=http://etcd-0.etcd.kube-system.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd.kube-system.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd.kube-system.svc.cluster.local:2380
          - --initial-cluster-state=new
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

        ports:
          - containerPort: 2379
          - containerPort: 2380
        volumeMounts:
          - name: etcd-data
            mountPath: /etcd-data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: etcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
